import runCollapsibleBar from "./CollapsibleBarStories";
import runDetailViewHeader from "./DetailViewHeaderStories";
import runDetailViewSection from "./DetailViewSectionStories";
import runDetailViewTable from "./DetailViewTableStories";
import runDetailViewTableSection from "./DetailViewTableSectionStories";
import runDetailViewThumbnails from "./DetailViewThumbnailsStories";
import runDetailViewThumbnailsSection
  from "./DetailViewThumbnailsSectionStories";
import runFlatButton from "./FlatButtonStories";
import runFooterBar from "./FooterBarStories";
import runHeaderBar from "./HeaderBarStories";
import runInputField from "./InputFieldStories";
import runLayerSelection from "./LayerSelectionStories";
import runLegend from "./LegendStories";
import runListSearchView from "./ListSearchViewStories";
import runLoginLogoutButton from "./LoginLogoutButtonStories";
import runModal from "./ModalStories";
import runPhotoView from "./PhotoViewStories";
import runRaisedButton from "./RaisedButtonStories";
import runSearchBar from "./SearchBarStories";
import runSearchResultCard from "./SearchResultCardStories";
import runSimpleLineChart from "./SimpleLineChartStories";
import runSnackBar from "./SnackBarStories";
import runTabBar from "./TabBarStories";
import runTimeseriesChart from "./TimeseriesChartStories";
import runToggleSwitch from "./ToggleSwitchStories";
import runViewSwitchButton from "./ViewSwitchButtonStories";

runCollapsibleBar();
runDetailViewHeader();
runDetailViewSection();
runDetailViewTable();
runDetailViewTableSection();
runDetailViewThumbnails();
runDetailViewThumbnailsSection();
runFlatButton();
runFooterBar();
runHeaderBar();
runInputField();
runLayerSelection();
runLegend();
runListSearchView();
runLoginLogoutButton();
runModal();
runPhotoView();
runRaisedButton();
runSearchBar();
runSearchResultCard();
runSimpleLineChart();
runSnackBar();
runTabBar();
runTimeseriesChart();
runToggleSwitch();
runViewSwitchButton();
